version: "{build}"

platform: x64

image: Visual Studio 2015

branches:
    only:
      - master

clone_depth: 10

skip_tags: true

environment:
  APM_TEST_PACKAGES:

  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - ps: Install-Product node 12

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

test: off
deploy: off
