#!/bin/bash

grep -ohr "fs\.\w*[(| ]" * --exclude-dir=node_modules --exclude-dir=learn-ide --exclude-dir=script | sed 's/^fs\.\(.*\).$/\1/' | sort -u > fs_occurences
grep -ohr "shell\.\w*[(| ]" * --exclude-dir=node_modules --exclude-dir=learn-ide --exclude-dir=script | sed 's/^shell\.\(.*\).$/\1/' | sort -u > shell_occurences
cat fs_occurences shell_occurences | sort -u > occurences
grep -ohr "\w*: [(|-]" learn-ide/adapters/* | sed 's/.\{3\}$//' | grep -v "constructor" | sort -u > coverage

echo "Diff of adapter usage vs coverage:"
diff occurences coverage
rm fs_occurences shell_occurences occurences coverage

echo "fs-plus references:"
ag 'fs-plus' --ignore-dir=spec --ignore-dir=learn-ide --ignore-dir=script --ignore=package.json

