#!/bin/bash

grep -ohr "fs\.\w*[(| ]" * --exclude-dir=node_modules --exclude-dir=nsync | sed 's/^fs\.\(.*\).$/\1/' | sort -u > fs_tree_view
grep -ohr "\w*: [(|-]" nsync/fs-override* | sed 's/.\{3\}$//' | sort -u > fs_nsync

echo "Taking diff of fs usage..."
diff fs_tree_view fs_nsync
rm fs_tree_view fs_nsync

echo "Checking for 'fs-plus' references..."
ag 'fs-plus' --ignore-dir=spec --ignore-dir=nsync --ignore=package.json

echo "Done."

