#!/bin/bash

grep -ohr "fs\.\w*[(| ]" * --exclude-dir=node_modules --exclude-dir=nsync | sed 's/^fs\.\(.*\).$/\1/' | sort -u > fs_tree_view
grep -ohr "\w*: [(|-]" nsync/fs-override* | sed 's/.\{3\}$//' | sort -u > fs_nsync
diff fs_tree_view fs_nsync
rm fs_tree_view fs_nsync

